version: '{build}'
os: Visual Studio 2017
build_script:
- ps: ./Build.ps1
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    APPVEYOR_REPO_TAG: true
